/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.basiccoffeecontroller;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.LinkedList;
import java.util.List;
import java.util.Queue;
import java.util.concurrent.BlockingQueue;
import java.util.concurrent.LinkedBlockingQueue;

public interface IBasicCoffeeControllerStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseChoice();
		
		public void raiseAmountVerified();
		
		public void raiseCanceled();
		
		public void raiseMoneyGiven();
		
		public void raiseAny();
		
		public void raiseReset();
		
		public void raisePaid();
		
		public void raiseFinish();
		
		public boolean isRaisedPay();
		
		public boolean isRaisedRefund();
		
		public boolean isRaisedGiveChange();
		
		public boolean isRaisedCheckAmount();
		
		public boolean isRaisedCancel();
		
		public boolean isRaisedStartRecipe();
		
		public boolean isRaisedClean();
		
		public boolean isRaisedRestart();
		
	public List<SCInterfaceListener> getListeners();
	}
	
	public interface SCInterfaceListener {
	
		public void onPayRaised();
		public void onRefundRaised();
		public void onGiveChangeRaised();
		public void onCheckAmountRaised();
		public void onCancelRaised();
		public void onStartRecipeRaised();
		public void onCleanRaised();
		public void onRestartRaised();
		}
	
	public SCInterface getSCInterface();
	
}
