/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.basiccoffeecontroller;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.List;

public interface IBasicCoffeeControllerStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseChose();
		
		public void raiseMoneyGiven();
		
		public void raiseAny();
		
		public void raiseCancel();
		
		public void raiseTakeOrder();
		
		public void raiseFinish();
		
		public boolean isRaisedUpdateOptions();
		
		public boolean isRaisedRefund();
		
		public boolean isRaisedGiveChange();
		
		public boolean isRaisedStartRecipe();
		
		public boolean isRaisedTimesup();
		
		public boolean isRaisedOrderVerified();
		
		public boolean isRaisedRestart();
		
		public boolean isRaisedWaitTakeOrder();
		
		public boolean isRaisedCloseDoor();
		
		public boolean isRaisedOpenDoor();
		
		public boolean isRaisedAdd10();
		
		public boolean isRaisedAdd15();
		
		public boolean isRaisedAdd20();
		
		public String getChoice();
		
		public void setChoice(String value);
		
		public long getPrice();
		
		public void setPrice(long value);
		
		public long getMoney();
		
		public void setMoney(long value);
		
		public long getOwnCup();
		
		public void setOwnCup(long value);
		
		public long getSucre();
		
		public void setSucre(long value);
		
		public long getTaille();
		
		public void setTaille(long value);
		
		public long getTemperature();
		
		public void setTemperature(long value);
		
		public long getEpice();
		
		public void setEpice(long value);
		
		public long getLait();
		
		public void setLait(long value);
		
		public long getCroutons();
		
		public void setCroutons(long value);
		
		public long getSirop();
		
		public void setSirop(long value);
		
		public long getGlace();
		
		public void setGlace(long value);
		
		public boolean getNfc();
		
		public void setNfc(boolean value);
		
		public long getCoffeeStock();
		
		public void setCoffeeStock(long value);
		
		public long getTeaStock();
		
		public void setTeaStock(long value);
		
		public long getIceTeaStock();
		
		public void setIceTeaStock(long value);
		
		public long getSoupStock();
		
		public void setSoupStock(long value);
		
		public long getExpressoStock();
		
		public void setExpressoStock(long value);
		
		public long getSucreStock();
		
		public void setSucreStock(long value);
		
		public long getSiropStock();
		
		public void setSiropStock(long value);
		
		public long getLaitStock();
		
		public void setLaitStock(long value);
		
		public long getGlaceStock();
		
		public void setGlaceStock(long value);
		
		public long getEpiceStock();
		
		public void setEpiceStock(long value);
		
		public long getCroutonStock();
		
		public void setCroutonStock(long value);
		
		public long getTpSachet();
		
		public void setTpSachet(long value);
		
		public long getTpChauffageEau();
		
		public void setTpChauffageEau(long value);
		
		public long getTpPosGobelet();
		
		public void setTpPosGobelet(long value);
		
		public long getTpPosDosette();
		
		public void setTpPosDosette(long value);
		
		public long getTpBonneTemperature();
		
		public void setTpBonneTemperature(long value);
		
		public long getTpEcoulement();
		
		public void setTpEcoulement(long value);
		
		public long getTpSucre();
		
		public void setTpSucre(long value);
		
		public long getTpSirop();
		
		public void setTpSirop(long value);
		
		public long getTpEpice();
		
		public void setTpEpice(long value);
		
		public long getTpBroyageGrains();
		
		public void setTpBroyageGrains(long value);
		
		public long getTpTassageGrains();
		
		public void setTpTassageGrains(long value);
		
		public long getTpInfusion();
		
		public void setTpInfusion(long value);
		
		public long getTpRetraitSachet();
		
		public void setTpRetraitSachet(long value);
		
		public long getTpGlaveVanille();
		
		public void setTpGlaveVanille(long value);
		
		public long getTpVerrouillagePorte();
		
		public void setTpVerrouillagePorte(long value);
		
		public long getTpDeverrouillagePorte();
		
		public void setTpDeverrouillagePorte(long value);
		
		public long getTpInjectionAzote();
		
		public void setTpInjectionAzote(long value);
		
	public List<SCInterfaceListener> getListeners();
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceListener {
	
		public void onUpdateOptionsRaised();
		public void onRefundRaised();
		public void onGiveChangeRaised();
		public void onStartRecipeRaised();
		public void onTimesupRaised();
		public void onOrderVerifiedRaised();
		public void onRestartRaised();
		public void onWaitTakeOrderRaised();
		public void onCloseDoorRaised();
		public void onOpenDoorRaised();
		public void onAdd10Raised();
		public void onAdd15Raised();
		public void onAdd20Raised();
		}
	
	public interface SCInterfaceOperationCallback {
	
		public boolean isCoffee();
		
		public boolean isTea();
		
		public boolean isExpresso();
		
		public boolean isSoup();
		
		public boolean isIceTea();
		
	}
	
	public SCInterface getSCInterface();
	
}
