/** Generated by YAKINDU Statechart Tools code generator. */
package fr.univcotedazur.polytech.si4.fsm.project.basiccoffeecontroller;

import fr.univcotedazur.polytech.si4.fsm.project.IStatemachine;
import fr.univcotedazur.polytech.si4.fsm.project.ITimerCallback;
import java.util.List;

public interface IBasicCoffeeControllerStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseChose();
		
		public void raiseMoneyGiven();
		
		public void raiseAny();
		
		public void raiseCancel();
		
		public void raiseTakeOrder();
		
		public void raiseReset();
		
		public void raiseFinish();
		
		public boolean isRaisedPay();
		
		public boolean isRaisedRefund();
		
		public boolean isRaisedGiveChange();
		
		public boolean isRaisedStartRecipe();
		
		public boolean isRaisedTimesup();
		
		public boolean isRaisedOrderVerified();
		
		public boolean isRaisedRestart();
		
		public boolean isRaisedWaitTakeOrder();
		
		public String getChoice();
		
		public void setChoice(String value);
		
		public long getPrice();
		
		public void setPrice(long value);
		
		public long getMoney();
		
		public void setMoney(long value);
		
		public long getSucre();
		
		public void setSucre(long value);
		
		public long getTaille();
		
		public void setTaille(long value);
		
		public long getTemperature();
		
		public void setTemperature(long value);
		
	public List<SCInterfaceListener> getListeners();
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceListener {
	
		public void onPayRaised();
		public void onRefundRaised();
		public void onGiveChangeRaised();
		public void onStartRecipeRaised();
		public void onTimesupRaised();
		public void onOrderVerifiedRaised();
		public void onRestartRaised();
		public void onWaitTakeOrderRaised();
		}
	
	public interface SCInterfaceOperationCallback {
	
		public boolean isCoffee();
		
		public boolean isTea();
		
		public boolean isExpresso();
		
	}
	
	public SCInterface getSCInterface();
	
}
